name: numix-icon-theme-square
title: Numix Square Icons
version: '25.01.31'
summary: Square is an app icon theme for Linux from the Numix project
description: |
  A snap for the Numix Square icon theme.

build-base: core20
base: bare
grade: stable
confinement: strict
license: GPL-3.0
icon: snap/local/numix.png

architectures:
  - build-on: amd64
    run-on: all

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/Numix-Square
        - $SNAP/share/icons/Numix-Square-Light

parts:
  icons:
    after:
      - utils
    plugin: dump
    source: "https://github.com/numixproject/numix-icon-theme-square/archive/refs/tags/$SNAPCRAFT_PROJECT_VERSION.tar.gz"
    override-build: |
        snapcraftctl build
        mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
        mv $SNAPCRAFT_PART_INSTALL/Numix* $SNAPCRAFT_PART_INSTALL/share/icons/
        $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons/Numix-Square*
        
  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
